### PR TITLE
More node detection fixes

### PR DESCRIPTION
**Pull request by schantaraud**
Sorry I missed a few instances of the same test in my previous PR.
Both node and browser tests pass in OpenPGP.js.

### CODE REVIEW

**Comment by twiss** [comment]
Thanks :+1: And sorry for the delay. Since they're now no longer one-liners and there's three of them, could you export an `isNode` constant in util.js and use that one in the other places?

**Comment by schantaraud** [comment]
Done

**Comment by twiss** [comment]
Thanks! Sorry for being nitpicky but I just meant a `const isNode = typeof global.process === 'object' &&
  typeof global.process.versions === 'object'` export. I know it's a function in OpenPGP.js but I think that's a bit silly too, it should never change so a function shouldn't be needed.

**Comment by schantaraud** [comment]
Yes, sorry I misread your comment, it makes sense.

**Comment by twiss** [comment]
:+1: Thanks!

**Pull request merged**
